swagger: '2.0'
info:
  title: User availability
  description: This section allow you to manage declared availability by users.
  version: "1.0.0"
# the domain of the service
host: cep.app
# array of all schemes that your API supports
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json  

# will be prefixed to all paths
basePath: /
paths:
  /availabilities:
    get:
      summary: Display user availability in selected period
      description: |
        Display user availability in selected period of time. For admin availability of all users will be returned but for other users it will be limited to users that are assigned to same projects
      tags:
        - User availability         
      parameters:
        - name: from
          in: query
          description: Date in format `YYYY-mm-dd`. This is first day from which users availability will be returned (It should be set to monday of current week)
          required: true
          type: string
        - name: limit
          in: query
          description: Number of days to get (default is `10`). If provided it should be `>0` and `<31`
          required: false
          type: number
          format: int
      responses:
        200:
          description: User availabilities
          schema: 
              $ref: "#/definitions/SuccessAvailabilityListResponse"
        422:
          description: Validation error. As code you will get `general.validation_failed`
          schema: 
              $ref: "#/definitions/ErrorResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema: 
              $ref: "#/definitions/ErrorResponse"     
  /availabilities/{userId}/{day}:                       
    get:
      summary: Get user availability for selected day
      description: |
          Display user availability for selected user in selected day
      tags:
        - User availability         
      parameters:
        - name: userId
          in: path
          description: User id
          required: true
          type: number
          format: int
        - name: day
          in: path
          description: Date in format `YYYY-mm-dd`.
          required: true
          type: string
      responses:
        200:
          description: List of user availabilities
          schema: 
              $ref: "#/definitions/UserAvailabilitiesResponse"
        422:
          description: Validation error. As code you will get `general.validation_failed`
          schema: 
              $ref: "#/definitions/ErrorResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema: 
              $ref: "#/definitions/ErrorResponse" 
    post:
      summary: Set user availability for selected day
      description: |
          Set user availability for selected user in selected day. This action will remove all user availability first and then will set it again based on given data
      tags:
        - User availability         
      parameters:
        - name: userId
          in: path
          description: User id
          required: true
          type: number
          format: int
        - name: day
          in: path
          description: Date in format `YYYY-mm-dd`.
          required: true
          type: string
        - name: availabilities
          in: body
          schema: 
            type: array
            description: User availabilities. If you want to remove all user availabilities, send it as empty array
            items: 
              $ref: "#/definitions/UserDayAvailability"
          
      responses:
        201:
          description: User availabilities successfully saved
          schema: 
              $ref: "#/definitions/UserAvailabilitiesResponse"
        422:
          description: Validation error. As code you will get `general.validation_failed`
          schema: 
              $ref: "#/definitions/ErrorResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema: 
              $ref: "#/definitions/ErrorResponse"                           
        
                      
definitions:
  SuccessAvailabilityListResponse:
    type: object
    properties:
      data:
        type: object
        properties:
          users:
            type: array
            description: Users that have any availability entries in selected period of dates
            items: 
              $ref: "#/definitions/User" 
          days:
            type: array
            description: Days in ascending order in selected period
            items: 
              $ref: "#/definitions/Day" 
          availabilities:
            type: array
            description: User day availability map
            items:
              $ref: "#/definitions/DayAvailability" 
      exec_time:
        type: number
        format: float
        description: API execution time
        
  User:
    type: object
    properties:
      id:
        type: number
        format: int
        description: User id
      email:   
        type: string
        description: User e-mail
      first_name:   
        type: string
        description: User first name
      last_name:   
        type: string
        description: User last name
      role_id:   
        type: number
        format: int
        description: User role id
      avatar:
        type: string
        description: User avatar
      deleted:
        type: number
        format: int
        description: Whether user has been deleted
      
  Day:
    type: object
    properties:
      date:
        type: string
        description: Date in format `YYYY-mm-dd`
        
  DayAvailability:
    type: object
    properties:
      date:
        type: string
        description: Date in format `YYYY-mm-dd`
      users:
        type: array
        description: Users that have any availability entry in this day
        items:
          $ref: "#/definitions/UserAvailability" 
      
  UserAvailability:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id of user
      availabilities:
        type: array
        description: Availabilities of user in single day
        items:
          $ref: "#/definitions/UserDayAvailability" 
          
  UserDayAvailability:
    type: object
    properties:
      time_start:
        type: string
        description: Start time (can be null)
      timestop:
        type: string
        description: Stop time (can be null)        
      available:
        type: number
        format: int
        description: Whether user is available in given time (or date if times are empty) or not
      description:
        type: string
        description: Optional description for this entry
        
        
  UserAvailabilitiesResponse:
    type: object
    properties:
      data:
        type: object
        properties:
          availabilities:
            type: array
            description: User availabilities
            items:
              $ref: "#/definitions/UserDayAvailability"
      exec_time:
        type: number
        format: float
        description: API execution time       
        
  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Error code.
      fields:
        type: array
        description: Error messages for each field. As keys you will get field names and as values you will get error messages for those fields
        items: 
          type: string
      exec_time:
        type: number
        format: float 
        description: API execution time
